# Generated by Django 5.0.4 on 2024-04-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0002_remove_catalogitem_catalog_delete_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('imatge', models.ImageField(default='default_item.jpg', upload_to='catalog_images')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.elementcatalog')),
            ],
        ),
        migrations.CreateModel(
            name='Peticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_peticio', models.DateField()),
                ('complerta', models.BooleanField(default=False)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Prestec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prestec', models.DateField()),
                ('data_retorn', models.DateField(blank=True, null=True)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.exemplar')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missatge', models.TextField()),
                ('data_registre', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.exemplar')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='TipusElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='catalog_item',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='elementcatalog',
            name='tipus_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibliotecaApp.tipuselement'),
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
        migrations.DeleteModel(
            name='Copy',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
